title: KoutQ8 - Buried Games Studio
description: Powered by Buried Games Studio
baseurl: "" # Leave empty if deploying to root (e.g. yourusername.github.io)
stylesurl: "/assets/styles"
url: "https://koutq8.buriedgames.com" # Change this to your actual domain

markdown: kramdown
theme: minima

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

include:
  - _pages
  - ".well-known"
